### ISSUE TITLE
GPG issue

### ISSUE THREAD

**Issue by jcubic** [openanalytics/r-base#2]
Not sure if you're aware but Ubuntu image seems to be broken. If you try to update or install anything it throw error:
```
GPG error: https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease:
The following signatures were invalid: EXPKEYSIG 51716619E084DAB9
Michael Rutter <marutter@gmail.com>
```
Here is article how to solve it:

https://www.bentoh.my/post/gpg-key-problem/

maybe it will be solved upstream but then the image need to be updated (rebuild).

**Comment by jcubic** [comment]
I'm not sure if broken image is with R 4 I'm using R 3.6 Maybe it's worth updating both versions.

**Comment by Dock3ric** [comment]
Hi, new GPG public key of Mr Rutter is "E298A3A825C0D65DFD57CBB651716619E084DAB9"
he has renewed his key in september for an expiration date of "2027-09-30" 
https://cran.r-project.org/bin/linux/ubuntu/

Please can you update the project ?

**Comment by mnazarov** [comment]
Thanks for noticing, this was fixed in https://github.com/openanalytics/r-base/commit/fe4299ed489ef2e35e6835f3464768cbcd2f3a7f but indeed the rebuild of previous images may be needed

**Comment by amorimt** [comment]
Thank you!
