### ISSUE TITLE
Dockerfile references non-existing domain

### ISSUE THREAD

**Issue by aowi** [openanalytics/r-base#4]
There are references to webproxy.openanalytics.eu in the Dockerfile. I assume this is an internal proxy. It doesn't resolve, at any rate:

```
$ host webproxy.openanalytics.eu
Host webproxy.openanalytics.eu not found: 3(NXDOMAIN)
```

This will make containers based on this one fail to build if they try to install additional packages:

```
W: Failed to fetch https://cloud.r-project.org/bin/linux/ubuntu/bionic-cran35/InRelease  Could not resolve 'webproxy.openanalytics.eu'
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by tverbeke** [comment]
Thanks for the feedback, @aowi Will fix asap

**Comment by tverbeke** [comment]
cleaned up and pushed to Docker hub

https://cloud.docker.com/u/openanalytics/repository/docker/openanalytics/r-base
