### ISSUE TITLE
Need update to R 4.1.x

### ISSUE THREAD

**Issue by sahemo** [openanalytics/r-base#5]
I am working in a project where I am using the `echarts4r` package. But it depends on [R (≥ 4.1.0)](https://cran.r-project.org/web/packages/echarts4r/index.html). Do you have a plan to update this in near future?

**Comment by dseynaev** [comment]
Hi @sahemo

4.1+ is as of recently supported in  `openanalytics/r-ver`

```
$ docker run -it --rm openanalytics/r-ver:4.1.2 R --version
R version 4.1.2 (2021-11-01) -- "Bird Hippie"
```
